#version: "3.9"

services:
  mongo:
    image: mongo:7
    container_name: lab-mongo
    hostname: mongo  # <--- ADICIONE ESTA LINHA
    command: ["mongod", "--replSet", "rs0", "--bind_ip_all"]
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    healthcheck:
      test: ["CMD-SHELL", "mongosh --quiet --eval \"db.adminCommand('ping').ok\" || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 10

  mongo-init:
    image: mongo:7
    container_name: lab-mongo-init
    depends_on:
      mongo:
        condition: service_healthy
    restart: "no"
    command:
      - sh
      - -c
      - |
        mongosh --host mongo:27017 --quiet --eval "try { rs.status() } catch(e) { rs.initiate({_id:'rs0', members:[{_id:0, host:'mongo:27017'}]}) }"

  redis:
    image: redis/redis-stack-server:latest
    container_name: lab-redis
    ports:
      - "6379:6379"
      - "8001:8001"
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "PING"]
      interval: 10s
      timeout: 5s
      retries: 10

  app:
    image: python:3.11-slim
    container_name: lab-app
    working_dir: /workspace
    volumes:
      - ./:/workspace
    environment:
      MONGO_URI: mongodb://mongo:27017/?replicaSet=rs0&directConnection=true
      MONGO_DB: radar_combustivel
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_DB: 0
      POLL_INTERVAL_SECONDS: 2
      BATCH_SIZE: 500
      BLOCK_SIZE: 10000
      CHECKPOINT_FILE: redis_indexes_checkpoint.json
    command: ["bash", "-lc", "pip install -r requirements.txt && sleep infinity"]
    depends_on:
      mongo:
        condition: service_healthy
      redis:
        condition: service_healthy

dashboard:
  image: python:3.11-slim
  container_name: lab-dashboard
  working_dir: /workspace
  volumes:
    - ./:/workspace
  ports:
    - "8501:8501"
  environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
  command: ["streamlit", "run", "queries/data-view.py", "--server.address=0.0.0.0"]
  depends_on:
    redis:
      condition: service_healthy

volumes:
  mongo_data:
  redis_data:
